### ISSUE TITLE
Mod not working with Glowing Womb

### ISSUE THREAD

**Issue by Araraura** [SalehAce1/FuryAlwaysOn#1]
Just at the title suggests, Glowing Womb isn't affected by the mod as it should.

**Comment by SalehAce1** [comment]
Wasn't this a mod you were going to make? I only made the first part for you to see the basics of making your mod, remember?

**Comment by Araraura** [comment]
> Wasn't this a mod you were going to make? I only made the first part for you to see the basics of making your mod, remember?

Yea, but I was never able to figure out how to activate Glowing Womb with it.
